language: node_js
node_js:
  - "8"
install:
  - yarn
script:
  - yarn run istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
